### ISSUE TITLE
renaming a project created using the template can't find manifest file

### ISSUE THREAD

**Issue by GusBeare** [ChrisHammond/DNNTemplates#11]
Hi

I have a project I created using the template. I wanted to clone this to modify for a different version.
So I copied the project to a new location and renamed everything. However, when I build I get this error:

Could not find file 'C:\Work\dnndev.me\DesktopModules\qAdsSearchTodos\qAdsSearch.dnn'.  

It's looking for the old project name and not the new one for the manifest file.

But I cannot find anywhere that this manifest file is named.  I can only guess that it gets compiled into a DLL when the project is first built from the template? But that doesn't seem at all sensible.

Is there any way around this issue?  Perhaps edit this line to hard code it in ModulePackage.Targets?

 XmlFileName="$(DNNFileName).dnn

Gus

**Comment by GusBeare** [comment]
It's not an ideal solution but that worked:

 XmlFileName="qAdsSearchTodos.dnn"

and I also had to change:

 <CreateItem Include="qAdsSearchTodos.dnn">

It would be helpful to know where $(DnnFileName) comes from and why.

Gus

**Comment by ChrisHammond** [comment]
It is defined in the PROJECT file, open that up the XML for the proj file and you'll find it towards the bottom I believe.

**Comment by GusBeare** [comment]
ah yes, thanks for much for the quick response!

**Comment by GusBeare** [comment]
```
 <PropertyGroup>
<Extension>zip</Extension>
<DNNFileName>qAdsSearchTodos</DNNFileName>
```
