### ISSUE TITLE
Are we going to wait for DNN 8 support

### ISSUE THREAD

**Issue by adopilot** [ChrisHammond/DNNTemplates#12]
Hello Chris,
First at all thanks on all great stuff you made in past years.
I know that You are in different flows now.

Are you planning any soon to upgrade Your templates to support developing modules in DNN 8
using MVC framework ?

**Comment by ChrisHammond** [comment]
Check out the releases tab

**Comment by adopilot** [comment]
Thanx,
My bad, i was not searching enough.
I'll try today and give feedback as soon.
Also, Do We need always to develop SPA modules using your template.
Or we can do something what is more looks like class MVC framework with routes and postbacks.

**Comment by ChrisHammond** [comment]
DNN has an MVC template, that was originally supposed to be submitted to this project, but they didn't end up making the submission. You might check their's out.
