### ISSUE TITLE
Template probably doesn't work on DNN 8

### ISSUE THREAD

**Issue by ghost** [ChrisHammond/DNNTemplates#13]
Hello,

I tried run my project on DNN 8 and I have some errors type:

> The type or namespace name '*' does not exist in the namespace 'DotNetNuke'

Where \* is for example: entities, UI, Security etc.

I tried it on 7.4.2 and don't have problems with run. 
Whether it's my fault or the template is not for Version 8?

====== EDIT
Probably my problem was target framework. I changed it to 4.5 from 4.0. After it can I use this module in 7 version?

====== EDIT 2
Problem still exist but only in *.ascx files, but I can compile module.

> The type or namespace name 'DotNetNuke' could not be found (are you missing a using directive or an assembly reference?)

**Comment by ChrisHammond** [comment]
What is the PATH of your project on the file system?

**Comment by ghost** [comment]
> C:\inetpub\wwwroot\dnn8_dev\DesktopModules\FormCreator
> and for dnn 7
> C:\inetpub\wwwroot\dnn7_dev\DesktopModules\FormCreator

Maybe problem is with Visual Studio 2015? (I created this in 2013).

> using DotNetNuke

It is marked in gray color. For dnn7 problem is too but only for views files (not .cs) and I don't have to change form 4.0 to 4.5 framework target.

**Comment by ChrisHammond** [comment]
For DNN8 you have to switch the project to compile to 4.5.1, after that it should build

**Comment by joannschlosser** [comment]
well, I am running DNN 8.0.0 switched to compile to 4.5.1 from 4.5.2, and I still get the same namespace error mentioned above.  This worked great in 7.   If I create a DNN7 DNNDEV.ME site and create the module there, will I be able to deploy it to a DNN8 site?

**Comment by WillStrohl** [comment]
I'm seeing this on VS 2015 Pro and and VS 2017 Pro on Windows Server 2012 and Windows 10 respectively, using the latest templates and they're compiled against .NET 4.5.1 (the default of the latest template).
