### ISSUE TITLE
Template doesn't work with Visual Studio 2015

### ISSUE THREAD

**Issue by ghost** [ChrisHammond/DNNTemplates#14]
Hello again,
I'm sorry that I write again in the same case, but quickly closed the my topic. I have problem with run DNN template on Visual Studio 2015. (dnn7 and dnn8)

I get the message from VS:

> The type or namespace name 'DotNetNuke' could nt be found...

This error display on all *.ascx files (not ascx.cs). I can compile project, I can install but Intellisense still show me red color errors.

Configuration app looks ok, I tried add/remove dotnetnuke references, tried change .NET Framework target. Always the same. I tried run project with VS 2013 and all looks ok. Problem is with old projects and new from template or it may be a problem with the configuration of the server?

My problem is similar to this: http://forums.ext.net/showthread.php?60405-CLOSED-Ext-Net-and-a-DotNetNuke-Module-Solution

**Comment by ChrisHammond** [comment]
This is a known issue with the intellisense in the ASCX. If you come up with a solution for this please let me know.

**Comment by hermesf** [comment]
Greetings, I have the same problem as mentioned "chosen one",.
there an alternative to work in VS 2015?

**Comment by Scippy** [comment]
Are you creating the new project template into DesktopModules/MVC folder?

**Comment by ghost** [comment]
I use a standard template (not MVC) everything is in the correct directory. The problem is only VS 2015.

**Comment by janadel** [comment]
Hi,
Are there any updates on this issue ?

**Comment by marcingarbarczyk** [comment]
Hello,
I'm not sure but I think found solution: remove files *.csproj.user and *.suo from project catalog.

Edit 07-11-2016
- Another solution but not cool is put dotnetnuke.dll to your solution folder.
- I had problem too with drag items from toolbox to editor s you can try different solutions from this thread http://stackoverflow.com/questions/9079466/visual-studio-popup-the-operation-could-not-be-completed

Be sure that no folder in the DNN in the IIS is not an application.
