### ISSUE TITLE
SPA module template and (standard) Module settings

### ISSUE THREAD

**Issue by ghost** [ChrisHammond/DNNTemplates#15]
I used SPA template to create new module and it was created and build fine.
But when enter the settings of the module there are only standard tabs: module settings, permissions and page settings. But template project contains the 'Settings.html'.
Manifest also contains it. If I change in manifest 'Settings' to 'QuickSettings' it works but how  to make standard settings?

**Comment by ChrisHammond** [comment]
This is corrected with the 7.0 release tonight.
