### ISSUE TITLE
Intellisense issue on MVC module template

### ISSUE THREAD

**Issue by Scippy** [ChrisHammond/DNNTemplates#16]
Your template is great and work fine, I'm able to install execute and debug the source code but opening .cshtml files I receive a lot of intellisense errors due to the fact in the first line the @model is not recognized.  
![screenshot](https://cloud.githubusercontent.com/assets/16607338/13628903/1ece70f4-e5d6-11e5-96bc-0667662274f3.jpg)

What could be the reason? how could I do to fix?
Very thanks!

**Comment by ChrisHammond** [comment]
I've got some changes that I'll work on in the next few weeks that I believe fixes some of these intellisense issues. Check out the changes I made over on my MessageOfTheDay repo https://github.com/ChrisHammond/MessageOfTheDay/commit/475f3fcc24613c3b0bd0acd6bbf0f46eca4aee20

**Comment by ChrisHammond** [comment]
Check out the 7.1 release for a fix https://github.com/ChrisHammond/DNNTemplates/releases/tag/v07.01.00

**Comment by Scippy** [comment]
Hi Chris,
a lot of intellisense issue are solved but now they have come out of new!

![screenshot1](https://cloud.githubusercontent.com/assets/16607338/13662655/77dde956-e69c-11e5-94f4-d0a9883bda5a.jpg)
![screenshot2](https://cloud.githubusercontent.com/assets/16607338/13662666/9449c326-e69c-11e5-82f2-2b5f0b25ad84.jpg)

but are you able to see them? or these issues affect only me?
Very thanks for the very fast response!
