### ISSUE TITLE
New intellisense issue on MVC module template

### ISSUE THREAD

**Issue by Scippy** [ChrisHammond/DNNTemplates#17]
Hi Chris,
a lot of intellisense issue are solved with latest 7.1 release but now they have come out of new!

![screenshot1](https://cloud.githubusercontent.com/assets/16607338/13696399/6c265dda-e766-11e5-8c77-1feb96a745c3.jpg)

![screenshot2](https://cloud.githubusercontent.com/assets/16607338/13696412/7822bc14-e766-11e5-9fa7-69a8e80d092a.jpg)

but are you able to see them? or these issues affect only me?
Very thanks for the very fast response!

**Comment by bhalmung** [comment]
Hi I have same issue.

**Comment by candelaere** [comment]
Had the same problem. Some of the references are broken, re-adding them fixes similar issues.

**Comment by bhalmung** [comment]
I copied the web.config contents from the module(solution) to the web.config in the dnn site.This solved the above issue.

**Comment by cklenk** [comment]
@bhalmung I tried that but it did not work for me. I tried rebuilding, clearing, unloading/reloading, etc. I'm on VS 2017.

Thanks
