### ISSUE TITLE
MSBuild.Community.Tasks.XmlRead task could not be loaded from the assembly

### ISSUE THREAD

**Issue by markdharley** [ChrisHammond/DNNTemplates#19]
I have the newest version installed (1.4.0.128) and I've modified the MSBuild.Community.Tasks.targets MSBuildCommunityTasksLib property to point to the correct folder, but I still get the following error when I try to build the project:

The "MSBuild.Community.Tasks.XmlRead" task could not be loaded from the assembly 
C:\inetpub\wwwroot\dnndev.me\DesktopModules\Statlant_DNN_Module\packages\MSBuildTasks.1.4.0.128\tools\MSBuild.Community.Tasks.dll. 
Could not load file or assembly 'file:///C:\inetpub\wwwroot\dnndev.me\DesktopModules\Statlant_DNN_Module\packages\MSBuildTasks.1.4.0.128\tools\MSBuild.Community.Tasks.dll' 
or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are 
available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

Am I missing something, or have I done something incorrectly?

**Comment by ChrisHammond** [comment]
Does that DLL file exist in that path? Did you happen to run the NUGET package installer for the latest version?

**Comment by markdharley** [comment]
Yes, the DLL does exist at that location. I used NUGET to do the installation for the latest version.

**Comment by GusBeare** [comment]
I have the same issue. Did you find a solution?

**Comment by GusBeare** [comment]
I found that if I delete the folder .build in the solution the issue goes away. That folder is created again when you build.

**Comment by GusBeare** [comment]
I found that in the .csproj file this line was incorrect:

```
<MSBuildCommunityTasksPath>$(SolutionDir)\packages\MSBuildTasks.1.5.0.196\tools</MSBuildCommunityTasksPath>
```

Once I edited the file and changed that to the correct version the issue went away.

**Comment by RubyRengeek** [comment]
Thanks GusBeare - this solved my problem.

**Comment by amirhz** [comment]
this works as a charm.

**Comment by charsoft** [comment]
Works for me; had to downgrade MSBuildTasks to version 1.5.0.196 to make it work though, FYI. Thanks for the tip!

**Comment by ransems** [comment]
> Works for me; had to downgrade MSBuildTasks to version 1.5.0.196 to make it work though, FYI. Thanks for the tip!

Had to do the same

**Comment by ransems** [comment]
Moved modubles to a new laptop, and had the same issue for all (5 different ones) and had to change the line in **BuildScripts\MSBuild.Community.Tasks.Targets** to:
`
    <MSBuildCommunityTasksLib>$(SolutionDir)packages\MSBuildTasks.1.4.0.128\tools\MSBuild.Community.Tasks.dll</MSBuildCommunityTasksLib>`
