### ISSUE TITLE
Error compiling 

### ISSUE THREAD

**Issue by bhattjidotcom** [ChrisHammond/DNNTemplates#21]
I am getting following error
![notabletorestorenugetpackages](https://cloud.githubusercontent.com/assets/10000502/14426216/fbb78f48-000a-11e6-8aee-79caf09a50a7.png)

**Comment by ChrisHammond** [comment]
What is the path of your module on file system?

**Comment by bhattjidotcom** [comment]
Problem solved after updating the Nuget package manager

**Comment by bhattjidotcom** [comment]
Tried the SPA Module,

gettting errors

![image](https://cloud.githubusercontent.com/assets/10000502/14428057/fdc3707c-0014-11e6-8d67-b7606c4eec92.png)

Severity    Code    Description Project File    Line    Suppression State
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 25  Active
Error   CS0234  The type or namespace name 'Http' does not exist in the namespace 'System.Web' (are you missing an assembly reference?) SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 4   Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 18  Active
Error   CS0012  The type 'AuthorizationFilterAttribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.    SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 18  Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 19  Active
Error   CS0012  The type 'AuthorizationFilterAttribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.    SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 19  Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 19  Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 21  Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 23  Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 34  Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 43  Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 50  Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 81  Active
Error   CS0246  The type or namespace name 'HttpPost' could not be found (are you missing a using directive or an assembly reference?)  SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 81  Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 82  Active
Error   CS0012  The type 'AuthorizationFilterAttribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.    SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 82  Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 83  Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 83  Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 98  Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 98  Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 116 Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ItemController.cs 116 Active
Error   CS0234  The type or namespace name 'Http' does not exist in the namespace 'System.Web' (are you missing an assembly reference?) SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\ServiceRouteMapper.cs 3   Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\UserController.cs 11  Active
Error   CS0012  The type 'AuthorizationFilterAttribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.    SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\UserController.cs 11  Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\UserController.cs 12  Active
Error   CS0012  The type 'AuthorizationFilterAttribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.    SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\UserController.cs 12  Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\UserController.cs 12  Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\UserController.cs 13  Active
Error   CS0012  The type 'ApiController' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Services\UserController.cs 17  Active
Warning CS7035  The specified version string does not conform to the recommended format - major.minor.build.revision    SpaDal2 C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2\Properties\AssemblyInfo.cs 34  Active
Warning     Could not resolve this reference. Could not locate the assembly "System.Net.Http.Formatting". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.   SpaDal2  
Warning     Could not resolve this reference. Could not locate the assembly "System.Web.Http". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.  SpaDal2  
Warning     Could not resolve this reference. Could not locate the assembly "System.Web.Http.WebHost". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.  SpaDal2  
Warning     The referenced component 'System.Net.Http.Formatting' could not be found.   SpaDal2  
Warning     The referenced component 'System.Web.Http' could not be found.  SpaDal2  
Warning     The referenced component 'System.Web.Http.WebHost' could not be found.  SpaDal2

**Comment by ChrisHammond** [comment]
Same question as before though.... What's your path? Looks like your references are all wrong

**Comment by bhattjidotcom** [comment]
Path of the Module is

C:\DNN\DnnDev\wwwroot\DesktopModules\MVC\SpaDal2

**Comment by ChrisHammond** [comment]
The spa module should be one folder higher, all the paths to your reference are wrong because of that
