### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by rajasajidmanzoor** [ChrisHammond/DNNTemplates#23]
Hello
Your package https://visualstudiogallery.msdn.microsoft.com/bdd506ef-d5c3-4274-bf1d-9e673fb23484 is not visible in Visual STudio Extension manager. i check this in both VS 2010 and 2013.
I have downloaded DNNTemplates.vsix and it is not installable on VS. see error below

![vsix cap](https://cloud.githubusercontent.com/assets/5917783/15580714/10da0234-2383-11e6-99a9-1411af3dc81a.PNG)

**Comment by rajasajidmanzoor** [comment]
Install Error Logs

5/26/2016 8:19:17 PM - Microsoft VSIX Installer
5/26/2016 8:19:17 PM - -------------------------------------------
5/26/2016 8:19:17 PM - Initializing Install...
5/26/2016 8:19:18 PM - Extension Details...
5/26/2016 8:19:18 PM -  Identifier      : e48e838a-c708-4d43-b822-4d5de0d13eed
5/26/2016 8:19:18 PM -  Name            : DotNetNuke Project Templates
5/26/2016 8:19:18 PM -  Author          : Chris Hammond
5/26/2016 8:19:18 PM -  Version         : 5.0
5/26/2016 8:19:18 PM -  Description     : This Visual Studio Package contains Project Templates to aid in your DotNetNuke Extension development.
5/26/2016 8:19:18 PM -  Locale          : en-US
5/26/2016 8:19:18 PM -  MoreInfoURL     : http://www.christoc.com/Products/Module-Development-Templates
5/26/2016 8:19:18 PM -  InstalledByMSI  : False
5/26/2016 8:19:18 PM -  SupportedFrameworkVersionRange : [4.0]
5/26/2016 8:19:18 PM - 
5/26/2016 8:19:18 PM -  Supported Products : 
5/26/2016 8:19:18 PM -      Microsoft.VisualStudio.Community
5/26/2016 8:19:18 PM -          Version : [14.0,15.0)
5/26/2016 8:19:18 PM - 
5/26/2016 8:19:18 PM -  References      : 
5/26/2016 8:19:18 PM -      -------------------------------------------------------
5/26/2016 8:19:18 PM -      Identifier   : Microsoft.VisualStudio.MPF.12.0
5/26/2016 8:19:18 PM -      Name         : Visual Studio MPF 12.0
5/26/2016 8:19:18 PM -      Version      : [12.0]
5/26/2016 8:19:18 PM -      MoreInfoURL  : 
5/26/2016 8:19:18 PM -      Nested       : No
5/26/2016 8:19:18 PM - 
5/26/2016 8:19:18 PM - 
5/26/2016 8:19:18 PM - Searching for applicable products...
5/26/2016 8:19:18 PM - Found installed product - Microsoft Visual Studio 2010 Ultimate
5/26/2016 8:19:18 PM - Found installed product - Microsoft Visual Studio Ultimate 2013
5/26/2016 8:19:18 PM - Found installed product - Microsoft Visual Studio Premium 2013
5/26/2016 8:19:18 PM - Found installed product - Microsoft Visual Studio Professional 2013
5/26/2016 8:19:18 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
5/26/2016 8:19:18 PM - Found installed product - Global Location
5/26/2016 8:19:18 PM - Found installed product - ssms
5/26/2016 8:19:18 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by ChrisHammond** [comment]
They are only for 2015, check out older releases on code Plex for 2013 support

**Comment by rajasajidmanzoor** [comment]
Hello ChrisHammond, I have download one from codeplex as well. it does not work. show same error. see
![snipvsix](https://cloud.githubusercontent.com/assets/5917783/15606965/d0d8fbbc-2428-11e6-80ce-f44b4a0a0d4c.PNG)

**Comment by rajasajidmanzoor** [comment]
I have downloaded V4.0 from Codeplex and it shows following error

![capture4 1](https://cloud.githubusercontent.com/assets/5917783/15607053/69af54b2-2429-11e6-85b2-4201174e422c.PNG)

Following is the Error Log

5/27/2016 4:43:37 PM - Microsoft VSIX Installer
5/27/2016 4:43:37 PM - -------------------------------------------
5/27/2016 4:43:38 PM - Initializing Install...
5/27/2016 4:43:39 PM - Extension Details...
5/27/2016 4:43:39 PM -  Identifier      : e48e838a-c708-4d43-b822-4d5de0d13eed
5/27/2016 4:43:39 PM -  Name            : DotNetNuke Project Templates
5/27/2016 4:43:39 PM -  Author          : Chris Hammond
5/27/2016 4:43:39 PM -  Version         : 4.1
5/27/2016 4:43:39 PM -  Description     : This Visual Studio Package contains Project Templates to aid in your DotNetNuke Extension development.
5/27/2016 4:43:39 PM -  Locale          : en-US
5/27/2016 4:43:39 PM -  MoreInfoURL     : http://www.christoc.com/Products/Module-Development-Templates
5/27/2016 4:43:39 PM -  InstalledByMSI  : True
5/27/2016 4:43:39 PM -  SupportedFrameworkVersionRange : [4.0]
5/27/2016 4:43:39 PM - 
5/27/2016 4:43:39 PM -  Supported Products : 
5/27/2016 4:43:39 PM -      Microsoft.VisualStudio.Pro
5/27/2016 4:43:39 PM -          Version : [12.0]
5/27/2016 4:43:39 PM -      Microsoft.VisualStudio.VWDExpress
5/27/2016 4:43:39 PM -          Version : [12.0]
5/27/2016 4:43:39 PM - 
5/27/2016 4:43:39 PM -  References      : 
5/27/2016 4:43:39 PM -      -------------------------------------------------------
5/27/2016 4:43:39 PM -      Identifier   : Microsoft.VisualStudio.MPF.12.0
5/27/2016 4:43:39 PM -      Name         : Visual Studio MPF 12.0
5/27/2016 4:43:39 PM -      Version      : [12.0]
5/27/2016 4:43:39 PM -      MoreInfoURL  : 
5/27/2016 4:43:39 PM -      Nested       : No
5/27/2016 4:43:39 PM - 
5/27/2016 4:43:39 PM - 
5/27/2016 4:43:39 PM - Searching for applicable products...
5/27/2016 4:43:41 PM - Found installed product - Microsoft Visual Studio 2010 Ultimate
5/27/2016 4:43:41 PM - Found installed product - Microsoft Visual Studio Ultimate 2013
5/27/2016 4:43:52 PM - The extension with ID 'e48e838a-c708-4d43-b822-4d5de0d13eed' is not installed to Microsoft Visual Studio Ultimate 2013.
5/27/2016 4:43:52 PM - Found installed product - Microsoft Visual Studio Premium 2013
5/27/2016 4:43:52 PM - Found installed product - Microsoft Visual Studio Professional 2013
5/27/2016 4:43:52 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
5/27/2016 4:43:52 PM - Found installed product - Global Location
5/27/2016 4:43:52 PM - Found installed product - ssms
5/27/2016 4:44:09 PM - The following target products have been selected...
5/27/2016 4:44:09 PM -  Microsoft Visual Studio Ultimate 2013
5/27/2016 4:44:09 PM - 
5/27/2016 4:44:10 PM - Beginning to install extension to Microsoft Visual Studio Ultimate 2013...
5/27/2016 4:44:10 PM - Install Error : Microsoft.VisualStudio.ExtensionManager.InstallByMsiException: The InstalledByMSI element in extension DotNetNuke Project Templates cannot be 'true' when installing an extension through the Extensions and Updates Installer.  The element can only be 'true' when an MSI lays down the extension manifest file.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)
