### ISSUE TITLE
Login link not working

### ISSUE THREAD

**Issue by improwise** [ChrisHammond/DNNTemplates#27]
Hi,

Just tried to generate a Skin using these templates in VS2015 for DNN 8.0.3 but it seems like the "login" link:

```
                <dnn:LOGIN ID="dnnLogin" CssClass="LoginLink" runat="server" LegacyMode="false"/>
```

Isn't showing up properly even in an unmodified skin (installed correctly via host). Other stuff seem to work though. Any ideas?

**Comment by improwise** [comment]
I guess there could be a breaking change in DNN 8 from DNN 7 causing this. Are there plans for DNN 8 versions of these templates?

**Comment by ChrisHammond** [comment]
I'll test it this week, my skin is working on all my dnn8 sites, so I'm not sure what you are experiencing

**Comment by improwise** [comment]
Yes, this is very weird, but the login/logout link just don't appear with no obvious reason for it. This in a almost freshly installed DNN 8.0.3 site. Other skins like Xcillion seem to work though.

**Comment by improwise** [comment]
Correction, I see now that the link does show up but for some reason the login link is in is white text which is almost impossible to see on the dark grey background. I've tried this in 2 different DNN 8 environment and the results as the same. So it is probably just a matter of updating CSS. 

Edit: 

I'm guessing the real problem might be that the blue background color does not show up as intended:

background-color: #178acc;

If it did, the white links would be more visible.

**Comment by ChrisHammond** [comment]
Thanks, I see the issue. Should have the code to fix this checked in shortly.

Well, until my machine froze up...

**Comment by improwise** [comment]
Happens even to the best of us sometimes. I hope you manage to get it sorted out without to much problem.

**Comment by ChrisHammond** [comment]
This was resolved back in June with a CSS fix
