### ISSUE TITLE
Some errors on Views about Html helper

### ISSUE THREAD

**Issue by Scippy** [ChrisHammond/DNNTemplates#28]
I've installed and all work fine, I'm able to debug without problem but I can see some Html helper errors opening view files on VS2015, see the image: 
![screenshotchrishammondtemplate](https://cloud.githubusercontent.com/assets/16607338/16370819/f194bf3a-3c42-11e6-8dc5-099f192019bf.jpg)
In other views there are errors on other html helper but with same error message.
I've tried to add the rerquested reference but it could not be added because already automatically referenced by the build system.
Any idea to fix it?

**Comment by baumerik** [comment]
hi, any updates to this?

**Comment by ChrisHammond** [comment]
No updates at this time. I haven't had time to look into it. 

The modules should still build find I believe?
