### ISSUE TITLE
Still getting warnings when using spa template...

### ISSUE THREAD

**Issue by aahock** [ChrisHammond/DNNTemplates#31]
Hey Chris:

I had thought the issue might have something to do with the 8.00RC version of DNN I was using, so I went and made a clean install of 8.0.3.

However, I still get these warnings.  I really hate working with any errors or warnings, and I would normally just fix this myself, but I can't find anything on the web that addresses what appears to be going on.
1. The specified version string does not conform to the recommended format.  I have zero clue why I am getting this, since the default format you have appears correct, but this is two separate version of dnn now and same message.  Any ideas?
2. I am getting a 'found conflict between separate versions of the same dependent assembly' warning, which needs to be addressed, or nothing will work.   Here's the specific error:

Severity    Code    Description Project File    Line    Suppression State
Warning     Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="Newtonsoft.Json" culture="neutral" publicKeyToken="30ad4fe6b2a6aeed" /><bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0" /></dependentAssembly></assemblyBinding> 

I have no clue here either, since I am using the spa template and have done nothing.  The JSON dll is version 7.0, as the above message states, and I can find no other version around, so I don't know how to fix this.  Do I have an old version of the template?  I know the whole spa 8 thing is really recent, but it's exactly how I want to build modules, since it uses as little of microsoft propietary stuff as possible (and after 25+ years of using Microsoft, I am finally smart enough to not lock myself in to things like 'asp code', etc.., that will just be changed at some point in the future.  At least with html/javascript/web api/and c# I know those will be supported years from now...)

Thanks for any help/comments...

I also have a question I can't find answered anywhere.  In a previous version of your tutorials, you recommended putting the 'services' folder off the desktop modules.  Now, I see you embed it inside a module folder.  How does one go about setting the web service up?  Do I need to create a web application still?  I can't find anything on this at all...kinda hard to get started if I can't get the service going...Is this now handled by DNN 8 or something?  Is that why it isn't mentioned at all?       

Oh, and just to be clear, I am using the DNN 8 SPA module template, DNN 8.0.3, and created the module project in the desktopmodules/ folder.  Am using latest IIS and the website shows up fine...just need to fix the above issues somehow...

**Comment by ChrisHammond** [comment]
I still get these, but will not be addressing these at this time. If someone comes up with a fix, I'll take a PR, but these don't cause any problems.
