### ISSUE TITLE
MVC Template doesn't install with Visual Studio 2015 Express

### ISSUE THREAD

**Issue by karthikeyanmlp** [ChrisHammond/DNNTemplates#33]
While installing the Template we getting following Error message.

**Installation Failed:** This extension is not installable on any currently installed products.

`Supported Products :`
`Microsoft.VisualStudio.Community`
`Version : [14.0,15.0)`

`Searching for applicable products...`
`Found installed product - Microsoft Visual Studio Express 2013 for Web`
`Found installed product - Microsoft Visual Studio Express 2015 for Web`
`Found installed product - Global Location`
`Found installed product - ssms`
`VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.`
`at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)`
`at VSIXInstaller.App.InitializeInstall()`
`at System.Threading.Tasks.Task.InnerInvoke()`
`at System.Threading.Tasks.Task.Execute()`

**Comment by ChrisHammond** [comment]
Sorry, I missed the "Subject" I'll work on getting it fixed for Express

**Comment by karthikeyanmlp** [comment]
Thanks @ChrisHammond  !

May I know, _**when will we get fixed release please?**_
_We are waiting for starting development._  if it is not a major change, I am ready to do that for make working on my side.
Please let me know.

**Comment by ChrisHammond** [comment]
Sorry, I was confused (damn VS for having too many editions)

You need to use the COMMUNITY version of VS2015 at minimum, not Express.

**Comment by karthikeyanmlp** [comment]
We are in production, so we are not having permission to use COMMUNITY(Open Source) version.

Please find the quoted line from [Licence for VS Community](https://www.visualstudio.com/support/legal/mt171547)
1. INSTALLATION AND USE RIGHTS > b. Organization licenses > [5]

> _**If you are an enterprise, your employees and contractors may not use the software to develop or test your applications**_, except for open source and education purposes as permitted above. 

Please help us to have template for Express or other versions.

**Comment by ChrisHammond** [comment]
Sorry, but this is not something I plan to support. It's open source though, so you can make changes yourself. Try modifying the vsixmanifest file (in the VSIX download) (extract it like a zip file)

**Comment by karthikeyanmlp** [comment]
Thanks a lot @ChrisHammond !

.VSIX installation support added for **Microsoft Visual Studio Express 2015 for Web** on following fork.
[@karthikeyanmlp/DNN.Templates](https://github.com/karthikeyanmlp/DNN.Templates)

Following .VSIX supports VS 2015 **Community** and **Express** versions
[DNNTemplates.vsix](https://github.com/karthikeyanmlp/DNNTemplates/blob/master/DNNTemplates.vsix)
[Dnn Mvc Module.vsix](https://github.com/karthikeyanmlp/DNN.Templates/blob/master/Dnn%20Mvc%20Module.vsix)
[Dnn Spa Module.vsix](https://github.com/karthikeyanmlp/DNN.Templates/blob/master/Dnn%20Spa%20Module.vsix)
