### ISSUE TITLE
Cannot find the DNN 8 VB Template for 2015

### ISSUE THREAD

**Issue by aahock** [ChrisHammond/DNNTemplates#39]
Sorry to put this here, but after two months of trying to find this on and off, by myself I give up.  Whenever I download the template vsix files, I get DNN 7 and 8 DAL2 for CSHARP, but only DNN 7 DAL2 for VB.

Can someone please point me to the DNN 8 DAL2 VB vsix template?  When attempting to use the current version (yes I just updated yet again) for a DNN 8 VB project, I get all kinds of errors with incompatibility with DNN libraries.  In other words template lib != dnn 8 libs.

I see that on the dnn forums someone else has asked this question, but rec'd a standard reply/non-reply, assuming that the DNN 8 vb template is in the releases, and I don't see it anywhere.

Please help...

**Comment by ChrisHammond** [comment]
It's all the same, just use the dnn7 one for vb. I don't have SPA or MVC versions for VB

**Comment by Scippy** [comment]
@aahock I've tried and I'm able to use vsix DNN 7 DAL2 VB on DNN8 website project without any problems.
Insured that website and module project have the same 4.5 target framework, and reference in the module project the following DNN 8 DLLs:
DotNetNuke
DotNetNuke.Web
DotNetNuke.WebUtility
