### ISSUE TITLE
Will not install on VS 2017

### ISSUE THREAD

**Issue by liffeyd** [ChrisHammond/DNNTemplates#41]
VS 2017 Community is installed on this PC but the template installer does not think so:

23/03/2017 08:36:30 - Searching for applicable products...
23/03/2017 08:36:32 - Found installed product - Microsoft Visual Studio Premium 2012 
23/03/2017 08:36:32 - Found installed product - Microsoft Visual Studio Professional 2012
23/03/2017 08:36:32 - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
23/03/2017 08:36:32 - Found installed product - Microsoft Visual Studio Professional 2013
23/03/2017 08:36:32 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
23/03/2017 08:36:32 - Found installed product - Microsoft Visual Studio Enterprise 2015
23/03/2017 08:36:32 - Found installed product - Microsoft Visual Studio Professional 2015
23/03/2017 08:36:32 - Found installed product - Microsoft Visual Studio Community 2015
23/03/2017 08:36:32 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
23/03/2017 08:36:32 - Found installed product - Global Location
23/03/2017 08:36:32 - Found installed product - ssms
23/03/2017 08:36:32 - Found installed product - ssms
23/03/2017 08:36:32 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by vespoli** [comment]
Having the same issue with VS 2015 Enterprise

**Comment by ChrisHammond** [comment]
Looks like you guys haven't grabbed the proper files for a version. I recommend going to the latest release and using the proper version of VS for that release at this time. Unfortunately with Codeplex's demise most of the "old" packages are gone
