### ISSUE TITLE
Module references physical path at development & not the virtual path

### ISSUE THREAD

**Issue by bhattjidotcom** [ChrisHammond/DNNTemplates#42]
Hi All

I have created a MVC Module using Christoc's latest templates. It all works fine, but the there is one very big issue (may be a bug)

It has cached the physical path where I had first time created the Module, and keeps referencing that path even if I install the module anywhere :(

I had created the Module at C:\WebSites\DnnDev\wwwroot\DesktopModules\MVC\MvcXYZ

and installed at http://dnn9.dnndev.me/Testimonial/MvcXYZ (physical folder at C:\WebSites\DNN9\wwwroot\DesktopModules\MVC\MvcXYZ)

Now, when I run the App, it looks for the files (all .cshtml and .resx file) at C:\WebSites\DnnDev\wwwroot\DesktopModules\MVC\MvcXYZ and not at ~/DesktopModules/MVC/MvcXYZ :(

What could be the issue? How to solve this? Please help

**Comment by VashJuan** [comment]
Curious too. Should the project be using relative paths, or maybe there's no option?
