### ISSUE TITLE
The Web server xx could not be found.

### ISSUE THREAD

**Issue by VashJuan** [ChrisHammond/DNNTemplates#43]
I've set up a fairly new (originally DNN v8.x, upgraded to DNN 9.1) instance of DNN that runs fine locally at http://dnndev.me/. I even moved the physical directory to c:/websites/dnndev.me in case that helped. It didn't. I've reread the old & current install instructions a few times.

I still get this error repeatedly - though the new DAL2 MVC module directory is created and populated:
![5-19-2017 at 11 47 05 am](https://cloud.githubusercontent.com/assets/8594671/26262973/9b598e30-3c8b-11e7-89cf-34b1a327942c.jpg)

The only issues I can think of:
- I'm running Windows 10 Pro and enabled the native IIS. (Is this the same as IIS Express?)
- I'm running Visual Stuidio 2017 Enterprise Edition. There was an old note mentioning the VSIX files might only run on Visual Studio Express? I've uninstalled and reinstalled the VSIX files from within Visual Studio - i.e., NOT using the ones from this GitHub repository.

What else can I look for or try?

Thanks!

**Comment by ChrisHammond** [comment]
Check to see if the Virtual Directory/app is configured in IIS

Check the desktopmodules folder

the MVC folder

and the module folder under there.

Chris


-----------------------
Chris Hammond
http://www.christoc.com

**Comment by VashJuan** [comment]
Brilliant Chris! Many thanks.

For others here's exactly what worked for me to move past the error:
Open IIS Manager, navigate to into Sites | DnnDev.me | DesktopModules |MVC |yourModuleName and right click on that. 

[The ~8MB directory with ~80 files were created already by Visual Studio as a result of creating the new project, filling out 2 dialogs and clicking OK. The error dialog was displayed, but the vitals WERE created.]

![5-19-2017 at 2 07 04 pm](https://cloud.githubusercontent.com/assets/8594671/26267593/e8b2ab44-3c9f-11e7-8ab1-1580a3caaa8f.jpg)

Select the "Convert to Application" option. The icon should change reflecting your choice. Close IIS Manager.

Return to Visual Studio and open 
C:\websites\dnndev.me\DesktopModules\MVC\yourModuleName\yourModuleName.csproj
Then **save all** (creating a project). 

Then change from debug to retail build.
![5-19-2017 at 2 35 34 pm](https://cloud.githubusercontent.com/assets/8594671/26267749/a5c4f200-3ca0-11e7-8d56-004c872a6c7c.jpg)

Right click on the solution (in Solution Explorer) and select "Build Solution"

{I get "warning CS7035: The specified version string does not conform to the recommended format - major.minor.build.revision" which I could ignore.] 

You should find the resulting extension's Install (and Source) ZIP files in the Install directory.

Go to your http://dnndev.me web site, add the extension you just created to the site, then add the extension to a page on the site, then in Edit Page mode, select the pencil icon at the upper right of the module to "Add an Item". 
![5-19-2017 at 2 41 13 pm](https://cloud.githubusercontent.com/assets/8594671/26267882/3b7981bc-3ca1-11e7-9dd6-9f7e29f4999c.jpg)
