### ISSUE TITLE
Request: possibility of adding EF Codefirst

### ISSUE THREAD

**Issue by azarbara** [ChrisHammond/DNNTemplates#45]
Could you please to add an option for creating MVC project with EntityFramework CodeFirst?

**Comment by SkyeHoefling** [comment]
I'm curious are you using EF CodeFirst in your DNN MVC Project? I recently used EF CodeFirst but I had to hack the SQL Provider Scripts to accomplish it so it really wasn't using code first as a full end-to-end solution with the .zip install files.

Sounds like this could be something useful but may not be a required dependency of this template in my opinion

**Comment by swalker1595** [comment]
Does anyone know how Entity Framework generates the SQL Scripts it uses in code-first?
