### ISSUE TITLE
using dojo AMD in SPA development

### ISSUE THREAD

**Issue by jeetu-gis** [ChrisHammond/DNNTemplates#46]
I am building a Map module using esri js api, which is built on dojo js framework (AMD), I get error : multidefine since the dojo loader is unable to load jQuery and KO libs, which are already loaded  into the DNN page's script tags.
Can you please let me know how I can work with AMD library and dojo loader with the SPA template

**Comment by swalker1595** [comment]
Did you ever figure this out? I am soon going to encounter the same problem...

**Comment by metronom72** [comment]
Because of this problems, i figure to use knockout
