### ISSUE TITLE
Allow a different default namespace for skins vs modules.

### ISSUE THREAD

**Issue by swalker1595** [ChrisHammond/DNNTemplates#48]
I would like to have a different default root namespace when using the theme template vs using the module template. For example, when creating a new module, I’d like the namespace to be: Walker.Dnn.Modules. When creating a theme I would like the default root namespace to be Walker.Dnn.Skins. 

Do you know of anyway that we can detect the template type in the Project Setup Wizard?

**Comment by swalker1595** [comment]
I have been unable to find any way to detect the project template inside of `SetupWizard`. The only way I see implementing this is to create 2 classes that inherit from `SetupWizard`. One could be called `ModuleSetupWizard` and `SkinSetupWizard` or something. 

We would then have to extract the properties `RootNameSpace, OwnerName, etc.` into the `SetupWizard`. They would need to be, atleast, `protected ` so that the derived classes could change them on initialization. 

Finally, in the .vstemplate, we could specify which class to use, `SetupWizard, ModuleSetupWizard, or SkinSetupWizard`.

**Comment by swalker1595** [comment]
Can we close this issue? PR #47

**Comment by ChrisHammond** [comment]
Closing issue for now as it will be included in the next release of the template project. Thanks for your contribution!
