### ISSUE TITLE
Intellisense Issue in MVC Templates

### ISSUE THREAD

**Issue by swalker1595** [ChrisHammond/DNNTemplates#51]
When using the DnnHtmlHelper Expressions, Visual Studio throws the exception:

"The type 'Expression<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'."

For example:

`@Html.TextBoxFor(m => Model.DisplayTime)`

Although a reference to System.Core already exist in the project.

As a work around, I copied the System.Core.dll into the DNNPlatform /bin/ folder. Is there a better way of handling this?

**Comment by cklenk** [comment]
@shanewalker1595 I have the same issue too! I tried your workaround but it says this component is already automatically referenced by the build system.

**Comment by ChrisHammond** [comment]
This isn't something I have found a fix for.
