### ISSUE TITLE
Packages folder not created when creating new desktop module with template

### ISSUE THREAD

**Issue by dcline97** [ChrisHammond/DNNTemplates#52]
Fresh install of VS 2017 community followed by an install of your current template from VS Gallery.  I created a new project using the template, but no packages folder got created and of course if I compile the new module no zip files re created because the folder is missing.

Help!

**Comment by dcline97** [comment]
Never mind - was compiling in Debug mode, not Release mode.

Working fine.

**Comment by ChrisHammond** [comment]
Glad you got it figured out!
