### ISSUE TITLE
Unable to create project

### ISSUE THREAD

**Issue by kietngo10** [ChrisHammond/DNNTemplates#53]
Getting this error when I attempt to create a project.  

![capture](https://user-images.githubusercontent.com/34072299/40508221-18f0a984-5f66-11e8-811c-6e73fe830dfe.PNG)

**Comment by ghost** [comment]
I am getting this same error. I'm on the latest Visual Studio 2017 Community version 15.8.5 running as Administrator.

**Comment by ChrisHammond** [comment]
Best advice I can recommend is to go through the process again and make sure you're following all the recommendations in my tutorials on environment setup.

https://www.christoc.com/Tutorials/DNN9-Tutorials

running IIS
running DNN in c:\websites\dnndev.me\
Run VS 2017 as an Admin
etc

**Comment by ghost** [comment]
Thanks for the advice. I retraced my steps and found out that somehow I missed installing the web development extension pack for VS 2017, Once that was installed the project template worked perfectly.

**Comment by ChrisHammond** [comment]
Awesome @davim00 thanks for the follow up!
