### ISSUE TITLE
Installer package created from template fails to install

### ISSUE THREAD

**Issue by dotcom9** [ChrisHammond/DNNTemplates#54]
Great templates! But I'm having a problem getting it to package dependency assemblies. The module .dnn file lists all of the assemblies my module needs in the component/assemblies section, but they are not being included in the install.zip. Do I need to modify the templates themselves so that dependencies are packaged, or have I missed a configuration elsewhere?

**Comment by ChrisHammond** [comment]
Have to modify the targets file to include additional dlls

**Comment by dotcom9** [comment]
Many thanks!
