### ISSUE TITLE
MVC Intellisense Issues

### ISSUE THREAD

**Issue by cklenk** [ChrisHammond/DNNTemplates#55]
Hello @ChrisHammond, I had a question. I am wondering why the razor intellisense only works when you have the vs solution within the dnn desktop modules folder. I have all the same references added to my project. I am not a fan of adding the solution right within the dnn folder structure. I like to structure my projects differently as I have many modules for many different customers, etc. Plus I like using the nuget package for dnn so I can build against different versions. If anyone has ideas that would be great!

Thanks

![image](https://user-images.githubusercontent.com/12185742/50298110-57e28780-044c-11e9-937e-15c48d63011a.png)

![image](https://user-images.githubusercontent.com/12185742/50298263-b90a5b00-044c-11e9-9ce4-9117caae2f09.png)

**Comment by ChrisHammond** [comment]
Sorry, this is not a model that I support, so I have no idea how to get the intellisense working outside the recommended way
