### ISSUE TITLE
Adding additional DLLs to be included during installation

### ISSUE THREAD

**Issue by swalker1595** [ChrisHammond/DNNTemplates#56]
I tried to following this guide: https://www.chrishammond.com/Blog/itemid/2053/including-additional-dllrsquos-in-an-msbuild-scr but was unsuccessful in packaging the additional DLLs for installation.

I added two lines to the `ModulePackage.targets` file:

        <Copy SourceFiles="$(MSBuildDnnBinPath)\$(AssemblyName).dll" DestinationFolder="$(MSBuildProjectDirectory)\Package\bin"/>
        <Copy SourceFiles="$(MSBuildDnnBinPath)\Microsoft.SharePoint.Client.dll" DestinationFolder="$(MSBuildProjectDirectory)\Package\bin"/>
        <Copy SourceFiles="$(MSBuildDnnBinPath)\Microsoft.SharePoint.Client.Runtime.dll" DestinationFolder="$(MSBuildProjectDirectory)\Package\bin"/>

And the following lines to my `.dnn` file:

        <assembly>
          <name>Microsoft.SharePoint.Client.dll</name>
        </assembly>
        <assembly>
          <name>Microsoft.SharePoint.Client.Runtime.dll</name>
        </assembly>

However the `install.zip` file does not contain either DLL.

**Comment by ChrisHammond** [comment]
Shane, did you get this resolved? Typically you need to copy the DLLs twice. one for the SOURCE package and one for the INSTALL package.

See this file as an example https://github.com/ChrisHammond/dnnCHAT/blob/master/BuildScripts/ModulePackage.targets
