### ISSUE TITLE
Latest Visual Studio 2019 Templates has extra http in there somewhere...

### ISSUE THREAD

**Issue by VashJuan** [ChrisHammond/DNNTemplates#57]
So, with these settings, on latest Win 10 Pro and latest Visual Studio Pro 2019:
![5-4-2019 at 6 11 29 PM](https://user-images.githubusercontent.com/8594671/57186706-0259c500-6e99-11e9-8a3c-3f01e1bb601d.jpg)
The next step is this error:
![5-4-2019 at 6 12 02 PM](https://user-images.githubusercontent.com/8594671/57186707-04bc1f00-6e99-11e9-9dbe-4fcdc8feafcb.jpg)
I've not searched into the code yet, but likely will...

**Comment by ChrisHammond** [comment]
Not able to repro this with the 10.2 release we've been testing.
