### ISSUE TITLE
Visual Studio 2019 SPA Module doesn't Migrate

### ISSUE THREAD

**Issue by VashJuan** [ChrisHammond/DNNTemplates#58]
These settings (latest Visual Studio 2019 Pro on latest Windows 10 Pro, running as Admin):
![5-4-2019 at 6 25 45 PM](https://user-images.githubusercontent.com/8594671/57186786-616c0980-6e9a-11e9-9b07-81a0d7b2585c.jpg)
Yields
![5-4-2019 at 6 26 03 PM](https://user-images.githubusercontent.com/8594671/57186788-6761ea80-6e9a-11e9-8dd1-c9bd8df4eef4.jpg)

**Comment by improwise** [comment]
I am having the same problem

Edit:

Please make  sure you use the correct URL, that seemed to fix it for me

**Comment by ChrisHammond** [comment]
Closing as not reproduceable in the latest 10.2 release testing we're doing using VS2019
