### ISSUE TITLE
The controller for path '/DNN/Default.aspx' was not found or does not implement IController.

### ISSUE THREAD

**Issue by webdbapps** [ChrisHammond/DNNTemplates#59]
I'm running DNN 9.3.2 and have received the following error when attempting to browse a page in my DNN site that contains a custom module:
The controller for path '/DNN/Default.aspx' was not found or does not implement IController.
System.Web.HttpException: The controller for path '/DNN/Default.aspx' was not found or does not implement IController. at System.Web.Mvc.DefaultControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType) at System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName) at DotNetNuke.Web.Mvc.Framework.Modules.ModuleApplication.ExecuteRequest(ModuleRequestContext context) at DotNetNuke.Web.Mvc.MvcHostControl.ExecuteModule() --- End of inner exception stack trace ---

My local IIS is pointed to c:\dnndev.me and the new module is located in DesktopModules\MVC.  I use Visual Studio 2019 Professional to develop, build and package the module.  

How do I resolve this error?

**Comment by ChrisHammond** [comment]
Where is the path /dnn/ coming from? Are you 100% positive that your module was created in the proper location?

**Comment by webdbapps** [comment]
So, I ensured that my local IIS website is pointed to c:\websites\dnndev.me and permissions are setup properly.  The custom module is in c:\websites\dnndev.me\DesktopModules\MVC\MyModuleName,

After ensuring that IIS is rendering the dnndev.me site, the error still persists as follows:
Error: SocialBodegaOnboarding is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: The controller for path '/Default.aspx' was not found or does not implement IController. ---> System.Web.HttpException: The controller for path '/Default.aspx' was not found or does not implement IController.at System.Web.Mvc.DefaultControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType)at System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName)at DotNetNuke.Web.Mvc.Framework.Modules.ModuleApplication.ExecuteRequest(ModuleRequestContext context)at DotNetNuke.Web.Mvc.MvcHostControl.ExecuteModule()--- End of inner exception stack trace ---

**Comment by lmakue** [comment]
Hi, would appreciate to know what your solution to this issue was as i am experiencing the same

**Comment by ransems** [comment]
had to edit the .dnn file, so this is not a problem, or an error. But if you rename or remove the Item controller, you need to wire up the location of the views for the new controller location. For instance, i removed the Item controller and added Login controller:
<controlSrc>UnionDev.Sso.UnionDevApiSso.Controllers/Login/Index.mvc</controlSrc>
