### ISSUE TITLE
Can't drop from toolbox

### ISSUE THREAD

**Issue by ExtraCrispyColonelAngus** [ChrisHammond/DNNTemplates#60]
Hi! I've been using your DNN templates for a while. They are awesome, I must say. Lately, I've been having an issue with both the 2017 and 2019 templates with new projects that are created (existing projects do not seem to have this issue). And the issue persists on two separate computers using these templates. The issue: Once I create the DNN project module template, I can't drag any items from my toolbox to the design or source tabs. Its the strangest thing Ive ever seen. All of the controls (with the exception of the HTML controls) refuse to drop on to the page. And its only with these templates. Have you seen this before? i tried repairing VS with no luck. Im baffled.

**Comment by ExtraCrispyColonelAngus** [comment]
Re-install fixed this issue.

**Comment by lvdevm** [comment]
> Re-install fixed this issue.

Hi ExtraCrispyColonelAngus,
I have the same issue, what did re-install  to fix it ? I did re-installed both VS & dnn template didn't fix. I have no clue what went wrong. I still can drag & drop the controls from the toolbox into other project templates but dnn template. Thanks
