### ISSUE TITLE
2019 VSIX

### ISSUE THREAD

**Issue by ExtraCrispyColonelAngus** [ChrisHammond/DNNTemplates#61]
Where is the DNN C# module file for 2019 from the latest VSIX? I do not see the compiled c# module for 2019..only 2017.

![qq](https://user-images.githubusercontent.com/31931936/64296859-2958fe00-cf42-11e9-84bb-9240188f56fe.PNG)

**Comment by ChrisHammond** [comment]
That's it, I just forgot to update text

**Comment by ChrisHammond** [comment]
Fixed this in the latest commit. Will get a new release out in the next couple of weeks.
