### ISSUE TITLE
Does not seem to work with VS2017 and VS2019

### ISSUE THREAD

**Issue by improwise** [ChrisHammond/DNNTemplates#62]
Have installed the templates via the VISX from Marketplace and installation seem to have gone fine, but the templates does not show up in neither 2017 nor 2019 when trying to create a new project.

**Comment by improwise** [comment]
I should add that they show up under extensions and are enabled there.

**Comment by improwise** [comment]
Actually, this might be a problem with VS more than the templates, there are numerous discussions about "custom project templates" not showing up these days in VS17 and VS19. Originally they only showed up in VS2019 Preview 4, but after a repair of VS2019 and reinstallation, they show up there as well.

**Comment by ChrisHammond** [comment]
I think this is a local issue, the current templates work fine with VS2019 from all our testing.
