### ISSUE TITLE
Exception: Input string was not in a correct format

### ISSUE THREAD

**Issue by micahsdad1402** [ChrisHammond/DNNTemplates#63]
When using SampleModule (Video 13), and no Assigned User is selected (there are none in the drop down), there is an exception from Edit.ascx.cs

Line 88: `AssignedUserId =  Convert.ToInt32(ddlAssignedUser.SelectedValue)`

Changed it to `AssignedUserId = (ddlAssignedUser.SelectedValue == "") ? 0 :  Convert.ToInt32(ddlAssignedUser.SelectedValue)`

**Comment by ChrisHammond** [comment]
Thanks for this @micahsdad1402 I will work to get this fix into a new release, along with a VB version of this fix as wel.

**Comment by ChrisHammond** [comment]
This is resolved in the 10.2 release coming ;)
