### ISSUE TITLE
The template installer is not working with vs 2017 at windows 7

### ISSUE THREAD

**Issue by rashidbilgrami** [ChrisHammond/DNNTemplates#64]
Hi, 
I have tried to install the template but its not available in a store. I downloaded   from the following URL https://marketplace.visualstudio.com/items?itemName=Chris-Hammond.DotNetNukeDNNDevelopmentProjectTemplates after that once I tried to run the error has displayed (please refer to the log file enclosed with this thread) 

[VSIXInstaller_83b411fa-376d-4310-b2bb-ca03f0f7ac8f.log](https://github.com/ChrisHammond/DNNTemplates/files/4830200/VSIXInstaller_83b411fa-376d-4310-b2bb-ca03f0f7ac8f.log)

**Comment by ChrisHammond** [comment]
The marketplace package only works work VS2019. You will need to download from GitHub releases for an older version
