### ISSUE TITLE
Minor error in Themes template

### ISSUE THREAD

**Issue by poul-erik** [ChrisHammond/DNNTemplates#65]
Hi Chris. 

I have used your templates a lot, mainly the MVC and SPA, but also the others though less frequently.

I have today multiple dnndev.me environments and when I want to create a new skin/theme using the template on a another environment (development.dnndev.me), the template creation fails. This does not happen for the other templates.

When I look in the template csproj I find that dnndev.me is hardcoded and not parameterized as in the other templates:

![billede](https://user-images.githubusercontent.com/38832672/124626472-fefa6380-de7e-11eb-8356-8b74bf64dccb.png)

Best regards

Poul Erik Sørensen

**Comment by ChrisHammond** [comment]
Thanks! I have fixed this in the code, it will be included in the next release.

**Comment by ChrisHammond** [comment]
Fixed in 10.3 release
