### ISSUE TITLE
Error on loading module.css for MVC module.

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [ChrisHammond/DNNTemplates#67]
I'm trying to use module.css within MVC Compiled Module, but it's simply not loading. In console there's this error:
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)    module.css`

And when I try to open link to module.css of my module in a separate tab I get this error text:
```
Server Error in '/desktopmodules/mvc/ModuleName' Application.
Could not load file or assembly 'DotNetNuke.HttpModules' or one of its dependencies. The system cannot find the file specified.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.IO.FileNotFoundException: Could not load file or assembly 'DotNetNuke.HttpModules' or one of its dependencies. The system cannot find the file specified.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Assembly Load Trace: The following information can be helpful to determine why the assembly 'DotNetNuke.HttpModules' could not be loaded.


WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Stack Trace:


[FileNotFoundException: Could not load file or assembly 'DotNetNuke.HttpModules' or one of its dependencies. The system cannot find the file specified.]
   System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type) +0
   System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName) +96
   System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase) +65
   System.Web.Compilation.BuildManager.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase) +62
   System.Web.Configuration.ConfigUtil.GetType(String typeName, String propertyName, ConfigurationElement configElement, XmlNode node, Boolean checkAptcaBit, Boolean ignoreCase) +50

[ConfigurationErrorsException: Could not load file or assembly 'DotNetNuke.HttpModules' or one of its dependencies. The system cannot find the file specified.]
   System.Web.Configuration.ConfigUtil.GetType(String typeName, String propertyName, ConfigurationElement configElement, XmlNode node, Boolean checkAptcaBit, Boolean ignoreCase) +572
   System.Web.Configuration.ConfigUtil.GetType(String typeName, String propertyName, ConfigurationElement configElement, Boolean checkAptcaBit) +31
   System.Web.Configuration.Common.ModulesEntry.SecureGetType(String typeName, String propertyName, ConfigurationElement configElement) +59
   System.Web.Configuration.Common.ModulesEntry..ctor(String name, String typeName, String propertyName, ConfigurationElement configElement) +59
   System.Web.HttpApplication.BuildIntegratedModuleCollection(List`1 moduleList) +221
   System.Web.HttpApplication.GetModuleCollection(IntPtr appContext) +1103
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +122
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +173
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +255
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +347

[HttpException (0x80004005): Could not load file or assembly 'DotNetNuke.HttpModules' or one of its dependencies. The system cannot find the file specified.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +552
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +122
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +737
```

I found some infor about IIS creating virtual directories when it's not needed. There was indeed "mvc" virtual directory under "DesctopModules", but when I deleted it and real "MVC" folder appeared - error didn't get fixed. Restarting iis, clearing website cache, restarting website via admin didn't help neither.

Is it a bug or am I missing something?

I'm using Windows 10, Visual Studio Community 2019 (v 16.11.2), DNN Project Templates 10.2.

**Comment by ChrisHammond** [comment]
Any other directories still look like they are virtual directories? Last thing to do is double check that the paths are 100% correct

/desktopmodules/mvc/modulename and not /desktopmodules/mvc/modulename/modulename

**Comment by Constantine-Ketskalo** [comment]
I checked paths again and they are correct. No other virtual directories.

**Comment by Constantine-Ketskalo** [comment]
Update: seems like this error occurs on attempt to include any css or js file in DNN MVC module.

**Comment by WillStrohl** [comment]
It would be useful for Chris (and others) if you could outline the specific steps you're taking to "include any CSS or js file" so that there are clear steps to reproduce the problem and possibly fix it.  🙂  Thanks!

**Comment by ChrisHammond** [comment]
I was able to create a new module with the 10.3 release, using the MVC template. Module.css seems to load just fine at this time. 

I was able to add CSS to the file and have those changes rendered on the page.

**Comment by Constantine-Ketskalo** [comment]
> It would be useful for Chris (and others) if you could outline the specific steps you're taking to "include any CSS or js file" so that there are clear steps to reproduce the problem and possibly fix it. 🙂 Thanks!

module.css should be included automatically for every module. So steps to reproduce are just create a new MVC module, install it and add to your page. That's it.

**Comment by Constantine-Ketskalo** [comment]
> I was able to create a new module with the 10.3 release, using the MVC template. Module.css seems to load just fine at this time.
> 
> I was able to add CSS to the file and have those changes rendered on the page.

Ok, thanks. Probably we'll update it to a newer version and try again. But I'll need to confirm it with my manager and do it later since right now I have other project that has higher priority. But thanks for your reply.

**Comment by jteliszczak** [comment]
> I was able to create a new module with the 10.3 release, using the MVC template. Module.css seems to load just fine at this time.
> 
> I was able to add CSS to the file and have those changes rendered on the page.

can we expect mentioned issue with another release f.e. 9.11.0?

**Comment by ChrisHammond** [comment]
> 

Not sure I understand what you are asking @jteliszczak. My testing seemed to show it worked fine so far. If people are having problems I need some recreation steps.

**Comment by jteliszczak** [comment]
> > 
> 
> Not sure I understand what you are asking @jteliszczak. My testing seemed to show it worked fine so far. If people are having problems I need some recreation steps.

I meant that the mentioned above issue with using module.css within MVC Compiled Module appeared with the DNN Platform v.09.10.02, the latest version, we can update is v.09.11.00. As you've mentioned before, you were able to create a new module with the 10.3 release. So I asked if we could have any issues with the v.09.11.00? Thank you in advance
