### ISSUE TITLE
DnnTemplate for visual studio 2022

### ISSUE THREAD

**Issue by naolarega** [ChrisHammond/DNNTemplates#69]
Since visual studio 2022 is released, it would be great if it had a dnn template extension for is.

**Comment by ChrisHammond** [comment]
I got started on that a while back but never finished! Will see if I can make some progress in the next week

**Comment by naolarega** [comment]
i am not sure if it is intensional. but when static content is build with the extension only javascript and css are left with install module resources. i had to decompress it and include all the necessary files and zip it again.

**Comment by ChrisHammond** [comment]
@naolArega I don't follow your question, but it sounds like a completely separate issue from your request for VS2022 support? If so please feel free to create a new issue with details

**Comment by naolarega** [comment]
ok my bad. thank you for your work too.

**Comment by ChrisHammond** [comment]
Latest release out! https://github.com/ChrisHammond/DNNTemplates/releases/tag/v11.00.00
