### ISSUE TITLE
Can't install DNN Templates on either Visual Studio Professional 2022 Version 17.1.0 or Visual Studio 2019 Professional Version 16.11.10

### ISSUE THREAD

**Issue by Tig7r** [ChrisHammond/DNNTemplates#71]
Hi There,

I am struggling to install the DNN Templates Extension on both VS2022 and VS2019.

VS2022
1. Via Extension Manager:
- Once I close Visual Studio I will get the following error:

2/24/2022 4:41:51 PM - Microsoft VSIX Installer
2/24/2022 4:41:51 PM - -------------------------------------------
2/24/2022 4:41:51 PM - vsixinstaller.exe version:
2/24/2022 4:41:51 PM - 17.1.1035-preview2
2/24/2022 4:41:51 PM - -------------------------------------------
2/24/2022 4:41:51 PM - Command line parameters:
2/24/2022 4:41:51 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\vsixinstaller.exe,/appidinstallpath:C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.exe,/skuName:Pro,/skuVersion:17.1.32210.238,/appidname:Microsoft Visual Studio Professional 2022,/culture:en-US,/noep,C:\Users\Admin\AppData\Local\Temp\VSIXutzupwqm.vsix
2/24/2022 4:41:51 PM - -------------------------------------------
2/24/2022 4:41:51 PM - Microsoft VSIX Installer
2/24/2022 4:41:51 PM - -------------------------------------------
2/24/2022 4:41:52 PM - Initializing Install...
2/24/2022 4:41:52 PM - Extension Details...
2/24/2022 4:41:52 PM - 	Identifier         : e48e838a-c708-4d43-b822-4d5de0d13eed
2/24/2022 4:41:52 PM - 	Name               : DNN Project Templates
2/24/2022 4:41:52 PM - 	Author             : Chris Hammond
2/24/2022 4:41:52 PM - 	Version            : 10.2
2/24/2022 4:41:52 PM - 	Description        : This Visual Studio Package contains Project Templates to aid in your (DNN) DotNetNuke Extension development of Themes and Modules. These templates require that you're running IIS locally and starting Visual Studio as an administrator. Fore more information visit https://www.christoc.com/Products/Module-Development-Templates

2/24/2022 4:41:52 PM - 	Locale             : en-US
2/24/2022 4:41:52 PM - 	MoreInfoURL        : https://christoc.com/Products/DNN-Development-Templates
2/24/2022 4:41:52 PM - 	InstalledByMSI     : False
2/24/2022 4:41:52 PM - 	SupportedFrameworkVersionRange : [4.0]
2/24/2022 4:41:52 PM - 
2/24/2022 4:41:52 PM - 	SignatureState     : Unsigned
2/24/2022 4:41:52 PM - 	Supported Products : 
2/24/2022 4:41:52 PM - 		Microsoft.VisualStudio.Community
2/24/2022 4:41:52 PM - 			Version : [16.0,17.0)
2/24/2022 4:41:52 PM - 			ProductArchitecture : x86
2/24/2022 4:41:52 PM - 
2/24/2022 4:41:52 PM - 	References         : 
2/24/2022 4:41:52 PM - 	Prerequisites      : 
2/24/2022 4:41:52 PM - 		-------------------------------------------------------
2/24/2022 4:41:52 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2/24/2022 4:41:52 PM - 		Name         : Microsoft.VisualStudio.Component.CoreEditor
2/24/2022 4:41:52 PM - 		Version      : [16.0,17.0)
2/24/2022 4:41:52 PM - 
2/24/2022 4:41:52 PM - Signature Details...
2/24/2022 4:41:52 PM - 	Extension is not signed.
2/24/2022 4:41:52 PM - 
2/24/2022 4:41:52 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.ComputeInstallableExtensions(IStateData stateData, Boolean isRepairSupported, Boolean isExtensionPack, IDictionary`2 skuDataMapping, IList`1 installableExtensionsPaths)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

2. When I download the latest VSIX file, it installs, but it never shows the module being installed on the Manage Extensions screen.
- I have checked the Extension Settings and enabled "Load Per user extensions when running as administrator",

I attempted the two methods above before installing VS2019, but I seem to get the same error. I have manually cleared the Extensions folder each time when I attempt to install the extension.

**Comment by ChrisHammond** [comment]
This was reported earlier this week to me directly, I will attempt to debug and track down why it isn't installing on anything other than the Community versions. It was intended to install on all versions of VS22.

**Comment by ChrisHammond** [comment]
I've corrected this with the V11.1 release for Visual Studio 2022, available on github and the VS Marketplace

**Comment by ChrisHammond** [comment]
https://github.com/ChrisHammond/DNNTemplates/releases/tag/V11.01.00

**Comment by Tig7r** [comment]
Hi Chris,

Thank you so much.

Thanks and Regards,
Zayne Repsold | Front End Web & Graphic Developer | Marketing
Tel: 011 607 7777
***@***.***<https://www.parrot.co.za/shop/product-filter?Category=248&brooms-and-mops>
***@***.***<https://www.youtube.com/channel/UCUxZxsTmeEKDYAESq-ZhG9g>  ***@***.*** <https://www.instagram.com/parrotproductssa/>   ***@***.*** <https://www.facebook.com/parrotproductssa/>    ***@***.*** <http://adessa.org.za/benefits/>
Parrot Products Group of Companies
Parrot Products (Pty) Ltd (South Africa)
22 Cleveland Road, Cleveland
Johannesburg, South Africa
Tel: +27 11 607 7600<tel:+27116077600>
Tel: +27 (0)10 1404 900<tel:+27101404900>

Parrot Presentation Products (Pty) Ltd (Namibia)
345 Cnr Nickel & Ongoporo Street
Prosperita, Windhoek, Namibia
Tel: +264 (0) 83 331 8110<+264833318110>

Parrot Presentation Products (Pty) Ltd (Botswana)
Unit 5 International Commerce Park,
Plot 183, West Avenue,
Gaberone, Botswana
Tel: +267 318 8799<+2673188799>

Parrot Presentation Products (Pty) Ltd (Zambia)
Stand No 12598B,
Mwembeshi Road,
Chinika West Industrial Area
Lusaka, Zambia
Tel: 00260 211 350020

Website: https://www.parrot.co.za<https://www.parrot.co.za/>
Please consider the environment before printing this mail.
