### ISSUE TITLE
DNN Template not showing under installed when opening Visual Studio 2022 in Adminstrator Mode

### ISSUE THREAD

**Issue by Tig7r** [ChrisHammond/DNNTemplates#72]
Hi There,

When I open Visual Studio Pro 2022 in Administrator mode, the installed extension does not show under the installed modules section.
It will show when you open VS2022 in normal mode.

Thank you

**Comment by ChrisHammond** [comment]
I am not experiencing that. I installed the extension yesterday on a clean install of VS2022 and no matter which mode I open VS22 Pro in, I see it installed and can create new projects with the templates?

![image](https://user-images.githubusercontent.com/1654166/155735036-69904dba-ef55-41e1-a50a-3a58ffd2287e.png)
