### ISSUE TITLE
Only first two custom settings save

### ISSUE THREAD

**Issue by Afacts** [ChrisHammond/DNNTemplates#74]
This is a strange issue that I can't figure out. The first two settings in settings.ascx.cs save but none after that. 
Below, NameOne and EmailOne save but not NameTwo and EmailTwo. Even looking directly in the DB there are no entries being addded to the ModuleSettings table for NameTwo and EmailTwo. 

Please advise. Not quite sure what I'm doing wrong. I'm following the pattern in the template. 

public override void UpdateSettings()
        {
            try
            {
                var modules = new ModuleController();

                modules.UpdateModuleSetting(ModuleId, "NameOne", txtName1.Text);
                modules.UpdateModuleSetting(ModuleId, "EmailOne", txtEmail1.Text);

                modules.UpdateModuleSetting(ModuleId, "NameTwo", txtName2.Text);
                modules.UpdateModuleSetting(ModuleId, "EmailTwo", txtEmail2.Text);
          }
}

**Comment by Afacts** [comment]
Hi, I'm wondering if you have any insights here. I don't doubt that I'm doing something wrong but I am pretty much doing it the same way that its done in the template. Are you able to save more than the first two?

**Comment by ChrisHammond** [comment]
I haven't had a chance to test this out yet. I will look at trying to reproduce it this week if I can

**Comment by Afacts** [comment]
Thanks so much for checking into it ...

**Comment by ChrisHammond** [comment]
Sorry for the delays, I finally got to testing this. I was able to setup 4 unique module settings and save them without problem. (using the C# DAL2 module template)

![image](https://user-images.githubusercontent.com/1654166/180929216-3f27430e-6fa0-462f-b8f8-71c6449db129.png)

Any chance you figured out what problem you were running into that caused this?
