### ISSUE TITLE
Problem with iPortable

### ISSUE THREAD

**Issue by jncraig** [ChrisHammond/DNNTemplates#78]
I created a new module called iPortableTest.  Then I started uncommenting the iPortable pieces in FeatureController.

I'm getting errors like this on line 55:

List<iPortableTestInfo> coliPortableTests = GetiPortableTests(ModuleID);

iPortableTestInfo and GetiPortableTests are both undefined.

Is the a bug or something that I did?

**Comment by ChrisHammond** [comment]
I honestly haven't touched iPortable in a number of years, so not 100% sure

**Comment by jncraig** [comment]
I think that this is a classic ID10T problem.  Cheers!

**Comment by ChrisHammond** [comment]
Most likely ;) 

Which template did you use? I'll try it out

**Comment by jncraig** [comment]
No, it's not a problem.

I got v10.? from the DNN store.

I think that the problem is that this version doesnt seem to create the "Items" list so the class and the controller don't exist with those names.  That easy enough for me to fix.

**Comment by ChrisHammond** [comment]
But there's DAL/DAL2/SPA/MVC/C#/VB.net, was hoping to try to recreate your experience

**Comment by jncraig** [comment]
I'll give it another shot, and hopefully I'll be careful this time!

**Comment by jncraig** [comment]
I went back and did things carefully.  

I think that the only problem was using IPortable in the module's name.  That confused things because IPortable was used in the namespace, and the compiler didn't like it.

I think ...

Aside from changing the module name, everything was successful.
